### ISSUE TITLE
getFileList implementation throws error

### ISSUE THREAD

**Issue by hlesesne** [codelathe/filecloudapi-php#2]
I am currently trying to execute an API method:

```php
  $list = $cloudAPI->getFileList("/myusername");
```
and it is returning an error on line [101](https://github.com/codelathe/filecloudapi-php/blob/master/fccloudapi.php#L101) of fccloudapi.php:

```
Error: Class '\codelathe\fccloudapi\\codelathe\fccloudapi\EntryRecord' not found
```

I see an EntryRecord defined on line [725](https://github.com/codelathe/filecloudapi-php/blob/master/fccloudapi.php#L725), but can't figure out what might be causing this error.

**Comment by hlesesne** [comment]
Should be fixed with pr #3

**Comment by madhankk** [comment]
Thanks for the report @jefersonralmeida will check your PR.

**Comment by jefersonralmeida** [comment]
Hey @hlesesne! We really appreciate your effort in reporting this bug to us, and spending your precious time to write a fix to it.

Your fix makes total sense in the way that the code was written, but we analyzed it and found a more elegant (but with bigger effort, since requires changes on many lines of code) fix. You can se the fix on this [PR](https://github.com/codelathe/filecloudapi-php/pull/4). We basic fixed the way that we call the Collection constructor, passing the class name using the `ClassName::class` sintax. This way we let PHP resolve the namespace for us. Please fell free to feedback, and send more PRs to us if you find any problem.

Thanks!
